config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  devise_for :users, controllers: {
      registrations: 'registrations'
  }

  resources :users do
    resources :events
  end

  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  serialize :recurring, Hash

  belongs_to :user

  validates :name, :start_time, presence: true
  validates :name, length: { maximum: 40 }

  def self.upcoming_events
    order('start_time asc').limit(5)
  end

  def recurring=(value)
    if RecurringSelect.is_valid_rule?(value)
      super(RecurringSelect.dirty_hash_to_rule(value).to_hash)
    else
      super(nil)
    end
  end

  def rule
    IceCube::Rule.from_hash recurring
  end

  def schedule(start)
    schedule = IceCube::Schedule.new(start)
    schedule.add_recurrence_rule(rule)
    schedule
  end

  def calendar_events(start)
    if recurring.empty?
      [self]
    else
      start_date = start.beginning_of_month.beginning_of_week
      end_date = start.end_of_month.end_of_week
      schedule(start_date).occurrences(end_date).map do |date|
        Event.new(id: id, name: name, start_time: date)
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :events

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def can_edit?(event)
    event.user == self
  end

  def to_s
    self.fullname ? self.fullname : self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update]
  before_action :set_user, only: [:edit, :create, :update]

  def index
    if params[:user_id]
      @events = current_user.events
    else
      @events = Event.all
    end
    @calendar_events = @events.flat_map{ |e| e.calendar_events(params.fetch(:start_date, Time.zone.now).to_date ) }
  end

  def show
    redirect_to edit_user_event_path(@event) if @event.user == current_user
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = @user.events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to user_events_path(user_id: current_user.id), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to user_events_path(user_id: current_user.id), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_event
      @event = Event.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    def event_params
      params.require(:event).permit(:name, :start_time, :recurring)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:fullname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:fullname, :email, :password, :password_confirmation, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_event.html.erb
<p>
  <%= link_to event.name, event %>
  <br>
  <small><%= event.start_time %></small>
</p>
<hr>

app/views/events/_form.html.erb
<div class="is-centered">

  <%= simple_form_for @event, html: { multipart: true } do |f| %>
    <%= f.error_notification %>

    <div class="field">
      <div class="control">
        <%= f.input :name, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :start_time , required: true, input_html: { class: "datetime"}, wrapper: false, label_html: { class:"label" } %>
      </div>
    </div>


    <div class="field">
      <%= f.label :recurring %>
      <%= f.select_recurring :recurring, nil, allow_blank: true %>
    </div>

    <div class="field is-grouped">
      <div class="control">
        <%= f.button :submit, class: 'button is-warning' %>
        <%= link_to 'Cancel', events_path, class:'button is-light' %>
      </div>
    </div>

  <% end %>
</div>

app/views/events/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <%= render 'form', event: @event %>
    </div>
  </div>
</section>

app/views/events/index.html.erb
<div class="columns">
  <div class="column is-9">

    <%= month_calendar events: @calendar_events do |day, events| %>
      <strong><small><%= day.to_s(:long) %></small></strong>
      <% events.each do |event| %>
        <div>
          <%= link_to event.name, event_path(event) %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="column is-3">
    <section class="section">
      <div class="title is-centered">
        Upcoming Events
      </div>

      <%= render(@events.upcoming_events) %>

    </section>
  </div>
</div>

app/views/events/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <%= render 'form', event: @event %>
    </div>
  </div>
</section>

app/views/events/show.html.erb
<div class="card-content">
  <p class="title">
    <%= @event.name %>
  </p>
  <p class="subtitle">
    <%= @event.start_time.strftime('%d.%m.%Y %H:%M')  %>
    by
    <%= @event.user.to_s  %>
  </p>
</div>
<% if current_user.can_edit?(@event) %>
  <%= link_to 'Edit', edit_event_path(@event), class: 'button is-warning is-outlined' %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-warning">
  <div class="navbar-brand">
    <%= link_to root_path, class:"navbar-item" do %>
      <h1 class="title is-5">FlatStackCalendar</h1>
    <% end  %>
    <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExampleTransparentExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to 'Calendar', root_path, class: 'navbar-item' %>
      <% if user_signed_in? %>
        <%= link_to 'My events', user_events_path(current_user), class: 'navbar-item' %>
        <%= link_to 'New event', new_user_event_path(current_user), class: 'navbar-item' %>
      <% end %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">

          <% if user_signed_in? %>

            <div class="navbar-item has-dropdown is-hoverable">
              <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
              <div class="navbar-dropdown is-right">
                <%= link_to current_user.fullname, edit_user_registration_path, class:"navbar-item" %>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
              </div>
            </div>
          <% else %>

            <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-warning" %>
            <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-warning"%>

          <% end %>

        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlatStackCalendar</title>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application' %>
</head>

<body class="<%= yield (:body_class) %>">

<%= render 'layouts/navbar' %>

<% if flash[:notice] %>
  <div class="notification is-success global-notification">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="notification is-danger global-notification">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>

<%= yield(:header) %>

<div class="container">

  <%= yield %>

</div>

</body>
</html>

app/views/simple_calendar/_month_calendar.html.erb
<section class="section">
    <div class="simple-calendar">
      <h1 class="title is-centered">
        <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view %>
        <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
        <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view %>
      </h1>

      <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
        <thead>
        <tr>
          <% date_range.slice(0, 7).each do |day| %>
            <th><%= t('date.abbr_day_names')[day.wday] %></th>
          <% end %>
        </tr>
        </thead>

        <tbody>
        <% date_range.each_slice(7) do |week| %>
          <tr>
            <% week.each do |day| %>
              <%= content_tag :td, class: calendar.td_classes_for(day) do %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

</section>